---
# install netbeans
# ref: https://www.howtoforge.com/how-to-install-netbeans-ide-on-ubuntu-2004/
# ref: https://netbeans.apache.org/download/index.html
# when use include_tasks, task name in included files won't appear. debug helps
- name: Show debug message
  debug:
    msg: ”task install netbeans"

# if check if the ln already exist
- name: check if file ln already exists
  ansible.builtin.stat:
    path: "/usr/local/bin/{{ netbeans_exec }}"
  register: netbeans_st

- name: unarchive package to /opt
  ansible.builtin.unarchive:
    src: "{{ netbeans_ins }}"
    dest: /opt
  when: not netbeans_st.stat.exists

- name: create symbolic link
  ansible.builtin.file:
    src: "/opt/{{ netbeans_path }}/bin/{{ netbeans_exec }}"
    dest: "/usr/local/bin/{{ netbeans_exec }}"
    state: link
    mode: '0755'

# create shortcut in menu for intellij
- name: copy template to guest
  ansible.builtin.template:
    src: "{{ netbeans_menu }}.j2"
    dest: "/opt/{{ netbeans_path }}/{{ netbeans_menu }}"
    mode: '0755'
  tags:
    - desktop

- name: install desktop shortcut 
  shell: "desktop-file-install /opt/{{ netbeans_path }}/{{ netbeans_menu }}"

