---
# install intellij
# ref: https://www.jetbrains.com/help/idea/installation-guide.html#standalone
# ref: https://github.com/nagygergo/jetbrains-toolbox-install/blob/master/jetbrains-toolbox.sh
- name: Task title- intellij
  debug:
    msg: start task intelliJ

# if check if the ln already exist
- name: check if file ln already exists
  ansible.builtin.stat:
    path: "/usr/local/bin/{{ intellij_exec }}"
  register: intellij_st

- name: unarchive package to /opt
  ansible.builtin.unarchive:
    src: "{{ intellij_ins }}"
    dest: /opt
  when: not intellij_st.stat.exists

- name: create symbolic link
  ansible.builtin.file:
    src: "/opt/{{ intellij_path }}/bin/{{ intellij_exec }}"
    dest: "/usr/local/bin/{{ intellij_exec }}"
    state: link
    mode: '0755'

# create shortcut in menu for intellij
- name: copy template to guest
  ansible.builtin.template:
    src: "{{ intellij_menu }}.j2"
    dest: "/opt/{{ intellij_path }}/{{ intellij_menu }}"
    mode: '0755'
  tags:
    - desktop

- name: install desktop shortcut 
  shell: "desktop-file-install /opt/{{ intellij_path }}/{{ intellij_menu }}"

