#!/usr/bin/env ansible-playbook
---
- name: Install system package python related
  hosts: vagrant1

  vars:
    proj_name: 'test_ansible'
    venv_home: "{{ ansible_env.HOME }}/.virtualenvs"
    venv_path: "{{ venv_home }}/{{ proj_name }}"
    reqs_path: '~/pip-pkg.txt'

  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: 
          - python3-pip
    - name: Create python3 virtualenv
      pip:
        name:
          - pip         
          - wheel
          - pytest
        state: latest
        virtualenv: "{{ venv_path }}"
        virtualenv_command: /usr/bin/python3 -m venv

    - name: Copy pip-pkg.txt to VM
      copy: 
        src: files/pip-pkg.txt
        dest: "{{ reqs_path }}"

    - name: Install packages listed in pip-pkg.txt under virtualenv
      pip:
        virtualenv: "{{ venv_path }}"
        requirements: "{{ reqs_path }}"
...