#!/usr/bin/env ansible-playbook
---
- name: Install system package python related
  hosts: vagrant1

  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: 
          - acl
          - python3-dev
          - python3-pip
          - python3-venv

...