#!/usr/bin/env ansible-playbook
---
- name: Install system package python related
  hosts: vagrant1

  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: 
          - python3-pip
    - name: Create python3 virtualenv
      pip:
        name:
          - wheel
          - pytest
          - Six
          - Pandas
          - Numpy
          - Docutils
        state: absent
...