#!/usr/bin/env ansible-playbook
---
- name: Install system package python related
  hosts: vagrant1

  vars:
    reqs_path: '~/pip-pkg.txt'

  tasks:
    - name: Install apt packages
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        pkg: 
          - python3-pip
    
    - name: pip install by name 
      pip:
        name:
          - pip         
          - wheel
          - pytest
        state: latest
    
    # install from file list
    - name: copy pip-pkg.txt to VM
      copy:
        src: files/pip-pkg.txt
        dest: "{{ reqs_path }}" 
        mode: 0644

    - name: install packages according to pip-pkg.txt
      pip:
        requirements: "{{ reqs_path }}"


...