# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  hosts=[
    ["vagrant1", "ubuntu/focal64", 2222, 8080, 8443],
    ["vagrant2", "ubuntu/focal64", 2200, 8081, 8444],
    ["vagrant3", "centos/stream8", 2201, 8082, 8445]
  ]

  # Use the same key for each machine
  config.ssh.insert_key = false


  hosts.each { |data|
    config.vm.define data[0] do |node|
      node.vm.box = data[1]
      node.vm.hostname = data[0]
      node.vm.network "forwarded_port", guest: 22, host: data[2], id: 'ssh'
      node.vm.network "forwarded_port", guest: 80, host: data[3], id: 'http'
      node.vm.network "forwarded_port", guest: 443, host: data[4], id: 'httpd'
      node.vm.provider "virtualbox" do |vb|
        vb.name = data[0]
        vb.linked_clone = true
      end
      node.vm.provision "shell", inline: "apt-get install -y acl"
    end
  }
end
