---
# tasks Test debug and install tree. 
# where Ansible find variables, please check README.md Requirements
- name: Show debug message
  debug:
    msg: ”task-tree show the variable {{ role_var1 }}“

- name: install tree
  become: true
  ansible.builtin.apt:
    name: tree
    state: present

- name: show current host name on this task
  debug:
    msg: “{{ inventory_hostname }} complete all tasks"
...