---
# install gnu compile suit
# ref: https://linuxconfig.org/how-to-install-gcc-the-c-compiler-on-ubuntu-22-04-lts-jammy-jellyfish-linux
# ref: https://www.cyberciti.biz/faq/howto-installing-gnu-c-compiler-development-environment-on-ubuntu/
# list: libc6-dev. gcc. g++. make, dpkg-dev
- name: Show debug message
  debug:
    msg: ”task install GNU GCC Compiler and Development Environment

- name: install dev packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - manpages-dev 
      - man-db 
      - manpages-posix-dev
    state: present