---
# tasks - Test debug and install tree. 
# req: var1 defined in default/
- name: use a wrong value
  debug:
    msg: ”show the variable {{ role_var1 }}“

- name: install tree
  become: true
  ansible.builtin.apt:
    name: tree
    state: present

- name: 
  debug:
    msg: “{{ inventory_hostname }} complete all tasks"
...
