---
# install ninja
# when use include_tasks, task name in included files won't appear. debug helps
# ref: https://ninja-build.org/
- name: Show debug message
  debug:
    msg: ”task install ninja“

- name: Install ninja“
  ansible.builtin.apt:
    pkg: ninja-build
    state: present